chore: add test suite
sabinebertram/ilp-spsp-pull-payment-server-test-suite pull request #1
Opened 2019-08-21 20:27 UTC by sabinebertram

2019-08-22 22:44 UTC, sharafian requested changes

2019-08-22 22:44 UTC, sharafian commented on index.js
> +  let run = async () => {
nitpick but these should be const

2019-08-22 22:44 UTC, sharafian commented on package.json
> +  "license": "ISC",
if this is we should use the Apache 2 license like other interledgerjs stuff if this might be moved under the interledgerjs org

2019-08-22 22:44 UTC, sharafian commented on src/helpers.js
> +class Helpers {
this is reinventing a lot of functionality that a testing framework like jest would give you for free. What's the rationale writing this yourself vs. writing this all as a suite of jest tests?

if you don't want to use jest you should consider outputting in some kind of format like tape that other tools will understand and be able to parse

2019-08-22 22:44 UTC, sharafian commented on README.md
> +First, connect to the network and have an instance of the ILP SPSP Pull Payment Server running. To run the entire test suite, run
when you say connect to the network you mean run moneyd?

2019-08-22 22:44 UTC, sharafian commented on src/config.js
> +    this.plugin = IlpPlugin()
you create a global plugin here but it looks like you also instantiate plugins elsewhere. Could we get rid of this global plugin on the config object?

2019-08-22 22:44 UTC, sharafian commented on src/pullfunctions.js
> +      let response = await fetch(this.config.url, {
const should be used everywhere unless you need to reassign a variable for some reason

2019-08-22 22:44 UTC, sharafian commented on src/pullfunctions.js
> +      let json = await response.json()
before getting the json you should check the boolean `response.ok` to make sure the response was 200-ish. What we've been using in other libraries lately is the axios library https://github.com/axios/axios which will actually throw on a non-200 response

2019-08-22 22:44 UTC, sharafian commented on src/pullfunctions.js
> +      return err
this try-catch appears to not do anything

2019-08-22 22:44 UTC, sharafian commented on src/pullfunctions.js
> +  createBody (amount, assetCode, assetScale, interval, cycles, cap) {
I think it's preferable to not use a helper function for this; using an object literal when constructing the body of your pull pointer creation request will make it clearer which fields mean which. Having this many positional arguments can be hard to read.

2019-08-22 22:44 UTC, sharafian commented on src/pullfunctions.js
> +  async pullMultipleIntervals (pointer, amount, n) {
rename n -> intervalCount (if I'm understanding that correctly)

2019-08-22 22:44 UTC, sharafian commented on src/pullfunctions.js
> +      let response = await fetch(this.config.url, {
config.url might be better named config.spspUrl, so it's clear what it's the URL of

2019-08-22 22:44 UTC, sharafian commented on src/pullfunctions.js
> +      return { totalReceive: 0, message: pulled.message }
totalReceive -> totalReceived, right?

2019-08-22 22:44 UTC, sharafian commented on src/pullfunctions.js
> +        let pulled = await this.pull(pointer, amount)
if one of these results in an error would we want to return right away? I think this could be written as a while-loop or a do-while if that's the case

2019-08-22 22:44 UTC, sharafian commented on src/pullfunctions.js
> +        await this.helpers.sleep(10000)
what's the rationale for using a 10 second timeout specifically?

2019-08-22 22:44 UTC, sharafian commented on src/testsuite.js
> +      return this
this will return a promise to `this`, not actually this. it'd probably be better to make people call the setup function by hand because it doesn't break people's assumptions as much

that said this is really interesting I didn't know you can return in a constructor

2019-08-22 22:44 UTC, sharafian commented on src/testsuite.js
> +    this.assetScale = String(this.details.assetScale - 1)
why are you subtracting 1 from the asset scale? is that to test that it can convert?

2019-08-22 22:44 UTC, sharafian commented on src/testsuite.js
> +    const creation = await this.pull.createPointer(this.pull.createBody(1, this.assetCode, this.assetScale, 'PT10S', 6, 'false'))
a lot of these constants are confusing if you don't know the context. it would be helpful to pull them out into named constants at the top of the file

2019-08-28 08:09 UTC, sabinebertram commented on src/pullfunctions.js
> +        await this.helpers.sleep(10000)
The interval of the pull pointer created is 10 seconds. But I probably shouldn't hard-code it.

2019-08-28 09:03 UTC, sabinebertram commented on src/pullfunctions.js
> +        let pulled = await this.pull(pointer, amount)
Yes I think so. I changed it into a while loop.

2019-08-28 09:14 UTC, sabinebertram commented on src/testsuite.js
> +      return this
removed this from the constructor

2019-08-28 09:18 UTC, sabinebertram commented on src/testsuite.js
> +    this.assetScale = String(this.details.assetScale - 1)
Yes, I wanted the pull payment agreement to be denominated in a different asset scale than the uplink. I could pull this apart and have a test that tests that it works with the same asset scale and then one with a different asset scale.

2019-08-28 09:19 UTC, sabinebertram commented on src/helpers.js
> +class Helpers {
This was pure ignorance. I'll look into jest and make use of it.

2019-08-31 15:55 UTC, sabinebertram commented on src/pullfunctions.js
> +        await this.helpers.sleep(10000)
Done

2019-08-31 15:56 UTC, sabinebertram commented on src/testsuite.js
> +    this.assetScale = String(this.details.assetScale - 1)
Done

2019-08-31 16:04 UTC, sabinebertram commented on src/helpers.js
> +class Helpers {
Done

2019-09-03 22:18 UTC, sharafian approved these changes

2019-09-03 22:18 UTC, sharafian commented on test/pullfunctions.test.js
> +    process.exit(1)
should print an error message

2022-04-22 09:14 UTC, merged